source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.9"
gem "csv"
gem "logger"
gem "base64"
gem "bigdecimal"
